version: "3.8"

services:
  mysqldb:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=zeus
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./app
    ports:
      - "8181:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/zeus",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: